logging:
  level:
    org:
      atmosphere: warn

server:
  port: 8080
vaadin:
  productionMode: true
  compatibilityMode: false
  pnpm:
    enable: false
spring:
  datasource:
    url: jdbc:mysql://awseb-e-qb2qvav2yk-stack-awsebrdsdatabase-zwpvjfys1uis.cllkds0lepes.us-east-1.rds.amazonaws.com:3306/ppln
    username: ppln
    password: goodmorningppln
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
  #  show-sql: true
    properties:
      hibernate:
#        enable_lazy_load_no_trans: true
        format_sql: true
    hibernate:
      ddl-auto: update
